# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "attachments", :force => true do |t|
    t.column "sample_id",    :integer, :null => false
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
  end

  create_table "groups", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "samples", :force => true do |t|
    t.column "recorded_at",      :datetime,                 :null => false
    t.column "user_id",          :integer,                  :null => false
    t.column "glucose",          :integer
    t.column "followup_glucose", :integer
    t.column "activity_type",    :string,   :default => "", :null => false
    t.column "carbohydrates",    :integer
    t.column "fat",              :integer
    t.column "protein",          :integer
    t.column "calories",         :integer
    t.column "time",             :integer
    t.column "comment",          :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "user_tag_descriptions", :force => true do |t|
    t.column "user_id",     :integer,  :null => false
    t.column "tag_id",      :integer,  :null => false
    t.column "description", :text
    t.column "created_at",  :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "first_name",                :string,   :limit => 50,  :default => "",    :null => false
    t.column "last_name",                 :string,   :limit => 50,  :default => "",    :null => false
    t.column "email",                     :string,   :limit => 200, :default => "",    :null => false
    t.column "handset_number",            :integer
    t.column "last_log_time",             :datetime
    t.column "admin",                     :boolean,                 :default => false
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "group_id",                  :integer,                                    :null => false
  end

end
