class AddUsersTable < ActiveRecord::Migration
  def self.up
    create_table :users do |t|
      # these fields are autogenerated and required by act_as_authenticated plugin
      t.column :login,                     :string
      t.column :crypted_password,          :string, :limit => 40
      t.column :salt,                      :string, :limit => 40
      t.column :remember_token,            :string
      t.column :remember_token_expires_at, :datetime
      # these fields are custom to ditag
      t.column :first_name,                :string, :limit => 50, :null => false
      t.column :last_name,                 :string, :limit => 50, :null => false
      t.column :email,                     :string, :limit => 200, :null => false
      t.column :handset_number,            :integer, :null => true
      t.column :last_log_time,             :datetime, :null => true
      t.column :admin,                     :boolean, :default => false
      t.column :created_at,                :datetime
      t.column :updated_at,                :datetime
    end
    #u = User.new(:login=>"admin", :password=>"ditagadmin", :password_confirmation=>"ditagadmin", 
    #        :first_name=>"Admin", :last_name=>"Admin", :email=>"Admin@ditag.com", :admin=>true).save!
  end

  def self.down
    drop_table :users
  end
end
